name: dart_cv
description: Create professional profile resumes using Flutter Widgets.
homepage: https://github.com/idootop/dart-cv

version: 1.0.0

environment:
  sdk: ^3.1.3

dependencies:
  pdf: ^3.10.8

dev_dependencies:
  lints: ^3.0.0
